image: mcr.microsoft.com/playwright:v1.58.2-noble

variables:
  PLAYWRIGHT_BROWSERS_PATH: $CI_PROJECT_DIR/pw-browsers

stages:
  - check

check:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - $PLAYWRIGHT_BROWSERS_PATH
  script:
    - npm install
    - npx playwright install chromium --with-deps
    - npm run test
  artifacts:
    when: on_failure
    paths:
      - playwright-report/
    expire_in: 1 week
